Simplify the NGINX Ingress guide
openservicemesh/osm-docs pull request #278
Opened 2021-11-10 00:11 UTC by draychev

This PR aims to simplify the doc guiding the OSM user through installation of NGINX Ingress Controller and integrating it with Open Service Mesh.

2021-11-10 23:57 UTC, shashankram requested changes
The changes look good, although it breaks the existing documentation by removing the examples for HTTP and HTTPS with TLS. We should document all 3 modes: 1. HTTP, 2. HTTPS with TLS, 3. HTTPS with mTLS.

2021-11-10 23:57 UTC, shashankram commented on content/docs/demos/ingress_k8s_nginx.md
> +The command below uses Helm to install NGINX Ingress Controller in the `ingress-nginx` namespace. For details and other options see the [NGINX](https://docs.nginx.com/nginx-ingress-controller/install
This link points to F5 Nginx, while the demo was meant to work with Kubernetes Nginx Ingress controller.

2021-11-10 23:57 UTC, shashankram commented on content/docs/demos/ingress_k8s_nginx.md
> +  -n kube-system \
`kube-system` is not correct.

2021-11-10 23:57 UTC, shashankram commented on content/docs/demos/ingress_k8s_nginx.md
> +OSM must be aware of the existence of an NGINX ingress pods. The NGINX pods will need a certificate to participate in the mesh. Edit the MeshConfig CRO named `osm-mesh-config` in the `osm-system` nam
Let's just `s/CRO/Custom Resource/g`

2021-11-12 17:28 UTC, draychev commented on content/docs/demos/ingress_k8s_nginx.md
> +kubectl label namespace ingress-nginx openservicemesh.io/monitored-by=osm
This is a good idea.  I'll keep both lines and explain why this is necessary somewhere at the end of the document.

2021-11-12 17:29 UTC, draychev commented on content/docs/demos/ingress_k8s_nginx.md
> +Look for the newly created mTLS certificate: `kubectl get secrets -n osm-system osm-ingress-mtls`
Thanks! I indeed changed the location of the secret to the `ingress-nginx` namespace.

2021-11-12 17:31 UTC, draychev commented on content/docs/demos/ingress_k8s_nginx.md
> -To verify that unauthorized clients are not allowed to access the backend, update the `sources` specified in the IngressBackend configuration. Let's update the principal to something other than the S
I don't think the verification belongs to this document. 

The goal of this document should be to provide crisp and clear steps on setting up nginx ingress. Verification and/or troubleshooting belong to a different document.

2021-11-12 17:33 UTC, draychev commented on content/docs/demos/ingress_k8s_nginx.md
> +- Port exposed to the Internet is `80`
I think the bash variables are smart but raise the bar for comprehension.  If we provide a base level with defaults -- the reader of this doc could choose to use bash or powershell or whatever variables they want and swap the defaults we have here.

2021-11-30 16:09 UTC, zr-msft commented on content/docs/demos/ingress_k8s_nginx.md
> +- Port exposed to the Internet is `80`
agreed with the sentiment around removing replaceable options and keeping defaults. Demoes should guide users down the *happy path* to complete a task with a verifiable result. Generalized advice for using a feature should be done outside the demo in other parts of the documentation

2022-07-25 16:09 UTC, shashankram commented
> @shashankram @nojnhuh Is there work we want to use from this PR? Should the merge conflict be fixed or should we close this and resume this work elsewhere? Is this work already largely done?



> @shashankram @nojnhuh Is there work we want to use from this PR? Should the merge conflict be fixed or should we close this and resume this work elsewhere? Is this work already largely done?

I believe the current demo is simple enough and follows a style consistent with the other demos. So my preference would be to drop this PR in favor of the existing demo guide.

2022-07-25 16:28 UTC, bridgetkromhout commented
@draychev Thanks again for helping us work through this. Sounds like we're happy with the complexity level the guide has currently, so I'm closing this PR now.

2022-07-25 16:28 UTC, closed without merging