Adds retry documentation and demo
openservicemesh/osm-docs pull request #369
Opened 2022-05-13 21:31 UTC by shalier

2022-05-13 21:34 UTC, shalier commented
In OSM v1.1.1 the Prometheus config does not contain the envoy retry metrics. Hold merge until the config has the metrics, because the demo relies on them

2022-05-17 19:02 UTC, nojnhuh requested changes
Overall looks good, just left a few comments for small stuff.

> In OSM v1.1.1 the Prometheus config does not contain the envoy retry metrics. Hold merge until the config has the metrics, because the demo relies on them

If the metrics are already included in `main` then that shouldn't block this PR since the live version of the docs are built from the release branch so the `main` branch here can stay in sync with the `main` branch of the code repo.

2022-05-24 21:55 UTC, shashankram reviewed
Nice doc @shalier

2022-05-24 21:55 UTC, shashankram commented on content/docs/demos/retry_policy.md
> +description: "Set up application with retry"
```suggestion
description: "Using retries to enhance service availability"
```

2022-05-24 21:55 UTC, shashankram commented on content/docs/demos/retry_policy.md
> +```bash
This an additional indent for correct formatting.

2022-05-24 22:03 UTC, shalier commented on content/docs/demos/retry_policy.md
> +  name: retry
The retry policy should still work even if it's in the `default` namespace, lmk if it doesn't work for you

2022-05-24 22:25 UTC, shashankram approved these changes

2022-05-25 15:25 UTC, nojnhuh commented on content/docs/demos/retry_policy.md
> +    source:
Looks like the indentation here is a bit off.

2022-05-26 15:57 UTC, nojnhuh approved these changes

2022-05-26 15:58 UTC, merged