Select only v1 in service in the demo
openservicemesh/osm-docs pull request #423
Opened 2022-07-26 00:03 UTC by jsturtevant

Signed-off-by: James Sturtevant <jstur@microsoft.com>

When running the demo at https://release-v1-2.docs.openservicemesh.io/docs/getting_started/traffic_split/#deploy-bookstore-v2-application even though the docs state: `The counter should not be incrementing because no traffic is flowing yet to the bookstore-v2 service.`

I was seeing traffic flow.  This was because the Kubernetes service was selecting all pods with the label `app: bookstore` where as it should have been selecting just v1.

This is a follow up to https://github.com/openservicemesh/osm-docs/pull/413 where this change was initially made

2022-07-26 12:49 UTC, keithmattix approved these changes
This makes sense to me based on #413.

2022-07-26 16:12 UTC, shashankram requested changes
As per #413, the root service selector should match the labels on the backend. With this change, the root service selector will not match the bookstore-v2 pod's selector. It seems like we will need to tweak the demo further to ensure we create a `bookstore-v1` service with `app:bookstore, version:v1`, and initially split traffic using the root `bookstore` service to `bookstore-v1` only if we want to only direct traffic to `v1` of the `bookstore` app. Then later, when we want to split traffic to `bookstore-v2` as well, we update the traffic split resource. With the changes made around root service usage, it seems like traffic will initially be directed to both bookstore-v1 and bookstore-v2 because both pods match the bookstore service selector, which is intended for the traffic splitting demo. 

The demo steps need a bit of tweaking. What you see is correct, but it is noted as unintended in the demo guide.

2022-07-27 18:35 UTC, shashankram approved these changes
Thanks @jsturtevant

2022-07-27 18:36 UTC, merged

2022-07-27 18:36 UTC, shashankram commented
@mergifyio backport release-v1.2