Fix wrong flags to osm install in OSM Manual Demo Guide
openservicemesh/osm-docs pull request #58
Opened 2021-05-19 09:19 UTC by eoftedal

2021-05-19 10:26 UTC, bridgetkromhout commented
Hi, @eoftedal! We'll review this PR, but meanwhile please sign your commit so we can merge if accepted? https://github.com/openservicemesh/osm-docs/pull/58/checks?check_run_id=2618664431 for details. Thanks!

2021-05-19 15:51 UTC, shashankram requested changes
Hey @eoftedal these changes you made are applicable to the v0.8 release, but not meant for the `main` branch. In `main`, the commands use the `--set` option.

2021-05-19 15:51 UTC, shashankram commented on content/docs/install/manual_demo.md
> -The `OpenServiceMesh.enablePermissiveTrafficPolicy` chart value instructs OSM to ignore any policies and
This is correct, but referring to the chart parameter in the `values.yaml` file. I think we should clarify this.

2021-05-19 15:51 UTC, shashankram commented on content/docs/install/manual_demo.md
> +    --deploy-grafana  --deploy-jaeger --deploy-prometheus
This is no longer true. The previous revision is correct.

2021-05-27 19:31 UTC, bridgetkromhout commented
Closing due to merge conflicts; superceded by https://github.com/openservicemesh/osm-docs/pull/103.

2021-05-27 19:31 UTC, closed without merging